config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :badges
    resources :categories
    resources :collections
    resources :inventories
    resources :trades
    resources :trade_badges
    resources :users
    resources :wishes

    root to: "badges#index"
  end

  get "/me", to: "users#me", as: :me
  patch "/me", to: "users#update"

  get "/users/:id", to: "users#show", as: :user
  get "/collections/:id", to: "collections#show", as: :collection
  get "/categories/:id", to: "categories#show", as: :category
  get "/search", to: "badges#search", as: :search

  get "/login", to: "users#login_page", as: :login_page
  post "/login", to: "users#login", as: :login

  get "/register", to: "users#register_page", as: :register_page
  post "/register", to: "users#register", as: :register

  delete "/logout", to: "users#logout", as: :logout

  scope :badges do
    get "/:id", to: "badges#show", as: :badge

    post "/:id/wish", to: "badges#wish", as: :wish
    post "/:id/unwish", to: "badges#unwish", as: :unwish
    post "/:id/inventory", to: "badges#inventory", as: :inventory
  end

  scope :trades do
    get "/:id", to: "trades#show", as: :trade
    post "/", to: "trades#create", as: :create_trade
  end

  get "/pages/:page", to: "pages#show", as: :pages

  root to: "collections#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged

  belongs_to :category, counter_cache: true
  belongs_to :collection, counter_cache: true

  has_many :inventories, dependent: :destroy
  has_many :users, through: :inventories

  has_many :wishes, dependent: :destroy
  has_many :wishers, through: :wishes, source: :user

  has_many :trade_badges, dependent: :destroy
  has_many :trades, through: :trade_badges

  has_attached_file :image,
    styles: {thumb: "50x50>" },
    url: "/sources/:hash.:extension",
    hash_secret: "ThisIsntProtectingAnythingJustWantADirectLink",
    default_url: "/missing.png"
  validates_attachment_content_type :image, content_type: [/\Aimage\/.*\z/]
end

app/controllers/admin/badges_controller.rb
module Admin
  class BadgesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Badge.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    def find_resource(param)
      Badge.friendly.find(param)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :signed_in?, except: [:show, :image]

  def show
    @badge = Badge.preload(:wishers, :users, :collection).friendly.find(params[:id])
    @inventory = @badge.inventories.find_by(user: current_user)&.number || 0

    @wishers = @badge.wishers
    @owners = @badge.users.preload(:inventories)
  end

  def wish
    current_user.wishes.find_or_create_by(badge_id: params[:id])

    respond_to do |format|
      format.json { head :ok }
    end
  end

  def unwish
    current_user.wishes.find_by(badge_id: params[:id])&.destroy

    respond_to do |format|
      format.json { head :ok }
    end
  end

  def inventory
    if params[:number].to_i > 0
      current_user.inventories.find_or_create_by(badge_id: params["id"]).update(number: params[:number])
    elsif params[:number].to_i == 0
      current_user.inventories.find_by(badge_id: params["id"])&.destroy
    end

    respond_to do |format|
      format.json { head :ok }
    end
  end

  def search
    wishes = []
    wishes = current_user.wishes.pluck(:badge_id) if current_user

    @badges = []
    Badge.where("name ~* ?", params[:search]).page(params[:page]).per(50).order(:id).group_by(&:collection).each do |collection, badges|
      @badges << { collection: collection.name, badges: []}

      badges.each do |badge|
        @badges.last[:badges] << {
          id: badge.id,
          name: badge.name,
          image: badge.image.url,
          link: badge_path(badge),
          wish: (wishes.include? badge.id)
        }
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @badges }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/search.html.erb
<div id="app">
  <div class="search-wrapper">
    <%= form_tag("/search", method: "get", class: "flexi-c r", id: "search") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "flexi-i search-field" %>
      <input class="flexi-i search-submit" type="submit"></input>
    <% end %>
  </div>

  <template v-for="group in result">
    <h3 class="year-title">{{ group.collection }}</h3>

    <div class="cards">
      <div
        v-for="badge in group.badges"
        class="card"
        :class="{'card-gold': badge.wish}">

        <% if current_user %>
          <div class="card-star" :class="{'active': badge.wish}" @click.prevent="wish(badge)"></div>
        <% end %>

        <a
          :href="badge.link"
          class="card-image"
          :style="{
            background: 'url('+badge.image+') no-repeat center',
            backgroundSize: 'contain'
          }"></a>
        
        <a :href="badge.link" class="card-title">{{ badge.name }}</a>
      </div>
    </div>
  </template>
</div>

<script>
  var vivi = new Vue({
    el: "#app",
    data: {
      page: 1,
      fetching: false,
      result: <%= raw @badges.to_json %>
    },
    methods: {
      wish: function(badge) {
        var toggle = (badge.wish ? "/unwish" : "/wish")

        fetch("/badges/"+badge.id+toggle,{
          method: "POST",
          headers: {
            "X-CSRF-Token": "<%= form_authenticity_token.to_s %>"
          },
          credentials: "same-origin"
        })
        .then(function(res){  
          badge.wish = !badge.wish
        })
        .catch(function(res){ console.log(res) })
      },
      nextPage: function(){
        var data = this.$data
        this.fetching = true
        data.page ++

        fetch("/search.json?search=<%= params[:search] %>&page="+data.page, {
          headers: {
            "Content-Type": "application/json",
            "X-CSRF-Token": "<%= form_authenticity_token.to_s %>"
          },
          credentials: "same-origin"
        })
        .then(res=>res.json())
        .then(function(res){  
          res.forEach( e => {
            var last = data.result[data.result.length-1]

            if (e.collection == last.collection) {
              last.badges = last.badges.concat(e.badges)
            } else {
              data.result = data.result.concat(e)
            }
          })

          data.fetching = false
        })
        .catch(function(res){ console.log(res) })
      }
    },
    mounted() {
      window.addEventListener('scroll', () => {
        if(window.pageYOffset + window.innerHeight >= document.documentElement.scrollHeight - 80) {
          if (!this.$data.fetching) {
            this.nextPage()
          }
        }
      })
    }
  });
</script>

app/views/badges/show.html.erb
<div id="app" class="flexi-c r">
  <div class="flexi-i side-bar">
    <div
      class="card"
      :class="{'card-gold': badge.wish}">
      
      <% if current_user %>
        <div class="card-star" :class="{'active': badge.wish}" @click.prevent="wish(badge)"></div>
      <% end %>

      <a
        :href="badge.link"
        class="card-image"
        :style="{
          background: 'url('+badge.image+') no-repeat center',
          backgroundSize: 'contain'
        }"></a>
      <a :href="badge.link" class="card-title">{{ badge.name }}</a>
      <div class="card-tag">
        <%= link_to @badge.collection.name, collection_path(@badge.collection_id) %>
      </div>
      <div class="card-tag">
        <span><%= @badge.year %></span>
      </div>
    </div>

    <% if current_user %>
      <p class="inventory">
        I have
        <input v-model="tmpInv" type="number" min="0" max="50" step="1"></input>
        of these
        <button v-if="tmpInv !== badge.inventory" @click="updateInventory(badge, tmpInv)">update</button>
      </p>
    <% end %>
  </div>

  <div class="flexi-i listing">
    <ul class="rows">
      <h3 class="year-title<%= @wishers.empty? ? ' cross' : '' %>">Wishers</h3>

      <% @wishers.each do |u| %>
        <li><%= link_to "#{u.username} (#{u.verified ? '' : 'un'}verified)", user_path(u) %></li>
      <% end %>
    </ul>

    <ul class="rows">
      <h3 class="year-title <%= @owners.empty? ? ' cross' : '' %>">Owners</h3>

      <% @owners.each do |u| %>
        <li><%= link_to "#{u.username} (#{u.verified ? '' : 'un'}verified) has #{u.inventories.find_by(badge_id: @badge.id)&.number || 0}", user_path(u) %></li>
      <% end %>
    </ul>
  </div>
</div>

<script>
  var vivi = new Vue({
    el: "#app",
    data: {
      badge: {
        id: <%= @badge.id %>,
        name: "<%= raw(@badge.name) %>",
        image: "<%= @badge.image.url %>",
        inventory: <%= @inventory %>,
        wish: <%= (current_user&.wish_items&.include? @badge) || false %>
      },
      tmpInv: <%= @inventory %>
    },
    methods: {
      wish: function(badge) {
        var toggle = (badge.wish ? "/unwish" : "/wish")

        fetch("/badges/"+badge.id+toggle,{
          method: "POST",
          headers: {
            "X-CSRF-Token": "<%= form_authenticity_token.to_s %>"
          },
          credentials: "same-origin"
        })
        .then(function(res){  
          badge.wish = !badge.wish
        })
        .catch(function(res){ console.log(res) })
      },
      updateInventory(badge, val) {
        fetch("/badges/"+badge.id+"/inventory",{
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRF-Token": "<%= form_authenticity_token.to_s %>"
          },
          body: JSON.stringify({number: val}),
          credentials: "same-origin"
        })
        .then(function(res){  
          badge.inventory = val
        })
        .catch(function(res){ console.log(res) })
      }
    },
  });
</script>