config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :badges
    resources :categories
    resources :collections
    resources :inventories
    resources :trades
    resources :trade_badges
    resources :users
    resources :wishes

    root to: "badges#index"
  end

  get "/me", to: "users#me", as: :me
  patch "/me", to: "users#update"

  get "/users/:id", to: "users#show", as: :user
  get "/collections/:id", to: "collections#show", as: :collection
  get "/categories/:id", to: "categories#show", as: :category
  get "/search", to: "badges#search", as: :search

  get "/login", to: "users#login_page", as: :login_page
  post "/login", to: "users#login", as: :login

  get "/register", to: "users#register_page", as: :register_page
  post "/register", to: "users#register", as: :register

  delete "/logout", to: "users#logout", as: :logout

  scope :badges do
    get "/:id", to: "badges#show", as: :badge

    post "/:id/wish", to: "badges#wish", as: :wish
    post "/:id/unwish", to: "badges#unwish", as: :unwish
    post "/:id/inventory", to: "badges#inventory", as: :inventory
  end

  scope :trades do
    get "/:id", to: "trades#show", as: :trade
    post "/", to: "trades#create", as: :create_trade
  end

  get "/pages/:page", to: "pages#show", as: :pages

  root to: "collections#index"
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId

  friendly_id :username, use: :slugged

  has_many :inventories, dependent: :destroy
  has_many :badges, through: :inventories

  has_many :wishes, dependent: :destroy
  has_many :wish_items, through: :wishes, source: :badge

  has_many :trade_badges, dependent: :destroy

  validates :email, presence: true, uniqueness: {message: "This email is already in use."}
  validates :username, presence: true, uniqueness: {message: "This username is already in use."}

  validates :name, presence: true
  validates :address, presence: true

  after_destroy :destroy_all_trades

  def trades
    Trade.where("a_id = ? OR b_id = ?", self.id, self.id)
  end

  def destroy_all_trades
    self.trades.destroy_all
  end

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    def find_resource(param)
      User.friendly.find(param)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in?, only: [:me, :update]

  def me
    @trades = current_user.trades
  end

  def show
    if params[:id].to_i == current_user&.id
      redirect_to me_path
      return
    end

    @user = User.preload(inventories: :badge).friendly.find(params[:id])
    @trades = @user.trades.where("a_id = ? OR b_id = ?", current_user.id, current_user.id).order("created_at DESC") if current_user
    @wishes = @user.wish_items.group_by(&:collection)
    @inventory = @user.badges.preload(:inventories).group_by(&:collection)
  end

  def login_page
    if current_user
      flash_messages << {text: "already signed in.", kind: "alert"}
      redirect_to "/me"
    end
  end

  def login
    user = User.find_by(email: params[:email])
    
    # password is type BCrypt::Password
    if user && user.password == params[:password] && !user.banned
      session[:user_id] = user.id

      flash_messages << {text: "Welcome back!", kind: "notice"}
      redirect_to root_path
    elsif user && user.password == params[:password] && user.banned
      flash_messages << {text: "This account has been suspended.", kind: "alert"}
      redirect_to login_path
    else
      flash_messages << {text: "incorrect email/password combination", kind: "alert"}
      redirect_to login_path
    end
  end

  def register_page
    if current_user
      flash_messages << {text: "already signed in.", kind: "alert"}
      redirect_to "/me"
    end
  end

  def register
    unless params["password"] == params["password_confirmation"]
      flash_messages << {text: "Password confirmation does not match.", kind: "alert"}
      redirect_to register_page_path
      return
    end

    unless params["password"]&.length >= 6
      flash_messages << {text: "Password must be at least 6 characters long.", kind: "alert"}
      redirect_to register_page_path
      return
    end

    user = User.new(
      email: params["email"],
      username: params["username"],
      name: params["name"],
      address: params["address"],
      password_hash: BCrypt::Password.create(params["password"])
    )

    if user.save
      session[:user_id] = user.id

      flash_messages << {text: "Welcome!", kind: "notice"}
      redirect_to root_path
    else
      user.errors.messages.each do |key, message|
        message.each do |text|
          flash_messages << {text: text, kind: "alert"}
        end
      end

      redirect_to register_page_path
    end
  end

  def update
    unless current_user.password == params[:password]
      flash_messages << {text: "Incorrect password.", kind: "alert"}
      redirect_to me_path
      return
    end

    current_user.name = params["name"]
    current_user.address = params["address"]

    if params["new_password"]&.present?
      unless params["new_password"] == params["new_password_confirmation"]
        flash_messages << {text: "Password confirmation does not match.", kind: "alert"}
        redirect_to me_path
        return
      end

      unless params["new_password"]&.length >= 6
        flash_messages << {text: "Password must be at least 6 characters long.", kind: "alert"}
        redirect_to me_path
        return
      end

      current_user.password_hash = BCrypt::Password.create(params["new_password"])
    end

    if current_user.save
      flash_messages << {text: "Account details updated.", kind: "notice"}
      redirect_to me_path
    else
      current_user.errors.messages.each do |key, message|
        message.each do |text|
          flash_messages << {text: text, kind: "alert"}
        end
      end

      redirect_to me_path
    end
  end

  def logout
    session[:user_id] = nil

    flash_messages << {text: "Successfully signed out", kind: "notice"}
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login_page.html.erb
<div class="account-box login">
  <%= form_tag("/login", method: "POST") do %>
    <h1>Login</h1>
    
    <label>Email</label>
    <input type="email" name="email" placeholder="abc@email.com" required></input>
    
    <label>Password</label>
    <input type="password" name="password" placeholder="●●●●●●●●" required></input>

    <div class="flexi-c rr">
      <input class="account-button" type="submit" value="Login"></input>
    </div>
  <% end %>
</div>

app/views/users/me.html.erb
<h1 class="section-title">Hi, <%= current_user.username %>!</h1>

<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openAccountDetails', 'accountItems', true)">
  <%= form_tag("/me", method: "PATCH") do %>
    <div class="flexi-c r">
      <h1 class="flexi-i">Account Details</h1>
      <div class="flexi-i account-box-open" id="openAccountDetails"></div>
    </div>

    <div class="hidden" id="accountItems">
      <div class="account-box-spacer"></div>

      <label>Email</label>
      <input type="email" name="email" placeholder="abc@email.com" value="<%= current_user.email %>" readonly></input>
      
      <label>Username</label>
      <input type="username" name="username" placeholder="abc_123" value="<%= current_user.username %>" readonly></input>

      <label>Full Name</label>
      <input type="text" name="name" placeholder="John Smith" value="<%= current_user.name %>" required></input>
      
      <label>Shipping Address</label>
      <input type="text" name="address" placeholder="10 Downing St, Westminster, London SW1A 2AA, UK" value="<%= current_user.address %>" required></input>

      <div class="hidden" id="editPassword">
        <label>New Password</label>
        <input type="password" name="new_password" placeholder="●●●●●●●●"></input>

        <label>Repeat New Password</label>
        <input type="password" name="new_password_confirmation" placeholder="●●●●●●●●"></input>
      </div>

      <label>Password</label>
      <input type="password" name="password" placeholder="●●●●●●●●" required></input>

      <div class="flexi-c rr">
        <input class="account-button" type="submit" value="Update"></input>
        <p class="account-button" id="passButton" onCLick="display(this, 'passButton', 'editPassword', false)">Change Password</p>
      </div>
    </div>
  <% end %>
</div>


<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openTrades', 'tradeItems', true)">
  <div class="flexi-c r">
    <h1 class="flexi-i">Trades</h1>
    <p class="flexi-i account-box-open" id="openTrades"></p>
  </div>

  <div class="hidden" id="tradeItems">
    <div class="account-box-spacer"></div>

    <ul class="rows">
      <% @trades.each do |trade| %>
        <li class="flexi-c r">
          <%= link_to "Status: #{trade.status}", trade_path(trade), class: "flexi-i" %>
          <%= link_to "With: #{trade.other(current_user).username}", trade_path(trade), class: "flexi-i" %>
          <%= link_to "created #{time_ago_in_words(trade.created_at)}", trade_path(trade), class: "flexi-i" %>
        </li>
      <% end %>
    </ul>

    <% if @trades.empty? %>
      <p class="account-centered">no trade history</p>
    <% end %>
  </div>
</div>


<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openWishes', 'wishItems', true)">
  <div class="flexi-c r">
    <h1 class="flexi-i">Wish List</h1>
    <div class="flexi-i account-box-open" id="openWishes"></div>
  </div>

  <div class="hidden" id="wishItems">
    <% current_user.wish_items.group_by(&:collection).each do |collection, badges| %>
      <h3 class="year-title"><%= collection.name %></h3>

      <div class="cards">
        <% badges.each do |b| %>
          <div class="card card-gold">
            <%= card_image(badge_path(b), b.image.url) %>
            <%= link_to b.name, badge_path(b), class: "card-title" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if current_user.wish_items.empty? %>
      <p class="account-centered">no items in wish list</p>
    <% end %>
  </div>
</div>


<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openInventory', 'inventoryItems', true)">
  <div class="flexi-c r">
    <h1 class="flexi-i">Inventory</h1>
    <div class="flexi-i account-box-open" id="openInventory"></div>
  </div>

  <div class="hidden" id="inventoryItems">
    <% current_user.badges.preload(:inventories).group_by(&:collection).each do |collection, badges| %>
      <h3 class="year-title"><%= collection.name %></h3>

      <div class="cards">
        <% badges.each do |b| %>
          <div class="card">
            <p class="card-inventory"><%= b.inventories.find_by(user_id: current_user.id).number %></p>

            <%= card_image(badge_path(b), b.image.url) %>
            <%= link_to b.name, badge_path(b), class: "card-title" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if current_user.badges.empty? %>
      <p class="account-centered">no items in inventory</p>
    <% end %>
  </div>
</div>


<script>
  function display(clicked, el_id, id, undoable) {
    var el = document.getElementById(el_id);

    if (document.getElementById(id).style.display == "block" && undoable) {
      if (el == clicked) {
        document.getElementById(id).style.display = "none";
        el.style.transform = "rotate(0deg)";
      }
    } else {
      document.getElementById(id).style.display = "block";
      
      if (undoable) {
        el.style.transform = "rotate(180deg)";
      } else {
        el.style.display = "none";
      }
    }
  }
</script>

app/views/users/register_page.html.erb
<div class="account-box login">
  <%= form_tag("/register", method: "POST") do %>
    <h1>Register</h1>
    
    <label>Email</label>
    <input type="email" name="email" placeholder="abc@email.com" required></input>
    
    <label>Username</label>
    <input type="username" name="username" placeholder="abc_123" required></input>

    <label>Full Name</label>
    <input type="text" name="name" placeholder="John Smith" required></input>
    
    <label>Shipping Address</label>
    <input type="text" name="address" placeholder="10 Downing St, Westminster, London SW1A 2AA, UK" required></input>

    <label>Password</label>
    <input type="password" name="password" placeholder="●●●●●●●●" required></input>
    
    <label>Repeat Password</label>
    <input type="password" name="password_confirmation" placeholder="●●●●●●●●" required></input>

    <div class="flexi-c rr">
      <input class="account-button" type="submit" value="Register"></input>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class="section-title"><%= @user.username %></h1>

<% if current_user %>
  <div class="account-box items-initially-hidden" onCLick="display(event.target, 'openTrades', 'tradeItems', 'newTrade', true)">
    <div class="flexi-c r">
      <h1 class="flexi-i">Trades</h1>

      <%= form_tag(create_trade_path, method: "POST", class: "flexi-i new-trade-button hidden", id: "newTrade") do %>
        <input type="hidden" name="user_id" value="<%= @user.id %>"></input>
        <input type="submit" value="Trade with <%= @user.username %> (<%= @user.verified ? '' : 'un' %>verified)"></input>
      <% end %>

      <p class="flexi-i account-box-open" id="openTrades"></p>
    </div>

    <div class="hidden" id="tradeItems">
      <div class="account-box-spacer"></div>

      <ul class="rows">
        <% @trades.each do |trade| %>
          <li class="flexi-c r">
            <%= link_to "Status: #{trade.status}", trade_path(trade), class: "flexi-i" %>
            <%= link_to "created #{time_ago_in_words(trade.created_at)}", trade_path(trade), class: "flexi-i" %>
          </li>
        <% end %>
      </ul>

      <% if @trades.empty? %>
        <p class="account-centered">no trade history with <%= @user.username %></p>
      <% end %>
    </div>
  </div>
<% end %>


<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openWishes', 'wishItems', false, true)">
  <div class="flexi-c r">
    <h1 class="flexi-i">Wish List</h1>
    <div class="flexi-i account-box-open" id="openWishes"></div>
  </div>

  <div class="hidden" id="wishItems">
    <% @wishes.each do |collection, badges| %>
      <h3 class="year-title"><%= collection.name %></h3>

      <div class="cards">
        <% badges.each do |b| %>
          <div class="card card-gold">
            <%= card_image(badge_path(b), b.image.url) %>
            <%= link_to b.name, badge_path(b), class: "card-title" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @wishes.empty? %>
      <p class="account-centered">no items in wish list</p>
    <% end %>
  </div>
</div>


<div class="account-box items-initially-hidden" onCLick="display(event.target, 'openInventory', 'inventoryItems', false, true)">
  <div class="flexi-c r">
    <h1 class="flexi-i">Inventory</h1>
    <div class="flexi-i account-box-open" id="openInventory"></div>
  </div>

  <div class="hidden" id="inventoryItems">
    <% @inventory.each do |collection, badges| %>
      <h3 class="year-title"><%= collection.name %></h3>

      <div class="cards">
        <% badges.each do |b| %>
          <div class="card">
            <p class="card-inventory"><%= b.inventories.find_by(user_id: @user.id).number %></p>

            <%= card_image(badge_path(b), b.image.url) %>
            <%= link_to b.name, badge_path(b), class: "card-title" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @inventory.empty? %>
      <p class="account-centered">no items in inventory</p>
    <% end %>
  </div>
</div>


<script>
  function display(clicked, el_id, id, extra_id, undoable) {
    var el = document.getElementById(el_id);

    if (document.getElementById(id).style.display == "block" && undoable) {
      if (el == clicked) {
        document.getElementById(id).style.display = "none";
        el.style.transform = "rotate(0deg)";

        if (extra_id) {document.getElementById(extra_id).style.display = "none";}
      }
    } else {
      document.getElementById(id).style.display = "block";
      
      if (undoable) {
        el.style.transform = "rotate(180deg)";
        if (extra_id) {document.getElementById(extra_id).style.display = "block";}
      } else {
        el.style.display = "none";
      }
    }
  }
</script>